package db

import (
	"context"
	"database/sql"
	"shopping/util"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
)

func createRandomCategory(t *testing.T) Category {
	category, err := testQueries.CreateCategory(context.Background(), CreateCategoryParams{
		Name: util.RandomName(),
		Description: util.RandomName(),
	})
	require.NoError(t, err)
	require.NotEmpty(t, category)
	
	// verify autogenerated ID and timestamps are set
	require.NotZero(t, category.ID)
	require.NotZero(t, category.CreatedAt)
	require.NotZero(t, category.UpdatedAt)

	return category
}

// creating categories
func TestCreateCategory(t *testing.T) {
	createRandomCategory(t)
}

// getting a single category
func TestGetCategory(t *testing.T) {
	category1 := createRandomCategory(t)
	category2, err := testQueries.GetCategory(context.Background(), category1.ID)
	require.NoError(t, err)
	require.NotEmpty(t, category2)

	require.Equal(t, category1.ID, category2.ID)
	require.Equal(t, category1.Name, category2.Name)
	require.WithinDuration(t, category1.CreatedAt, category2.CreatedAt, time.Second)
	require.WithinDuration(t, category1.UpdatedAt, category2.UpdatedAt, time.Second)
}

/// updating a product by id
func TestUpdateCategory(t *testing.T) {
	category1 := createRandomCategory(t)

	arg := UpdateCategoryParams{
		ID: category1.ID,
		Name: util.RandomName(),
	}

	category2, err := testQueries.UpdateCategory(context.Background(), arg)
	require.NoError(t, err)
	require.NotEmpty(t, category2)

	require.Equal(t, category1.ID, category2.ID)
	require.Equal(t, arg.Name, category2.Name)
	require.WithinDuration(t, category1.CreatedAt, category2.CreatedAt, time.Second)
	require.WithinDuration(t, category1.UpdatedAt, category2.UpdatedAt, time.Second)
}

// listing categories
func TestListCategory(t *testing.T) {
	for i := 0; i < 10; i++ {
		createRandomCategory(t)
	}

	arg := ListCategoriesParams{
		Limit: 5,
		Offset: 5,
	}

	categories, err := testQueries.ListCategories(context.Background(), arg)
	require.NoError(t, err)
	require.Len(t, categories, 5)

	for _, category := range categories {
		require.NotEmpty(t, category)
	}
}

func TestDeleteCategory(t *testing.T) {
	category1 := createRandomCategory(t)
	err := testQueries.DeleteCategory(context.Background(), category1.ID)
	require.NoError(t, err)

	category2, err := testQueries.GetCategory(context.Background(), category1.ID)
	require.Error(t, err)
	require.EqualError(t, err, sql.ErrNoRows.Error())
	require.Empty(t, category2)
}