// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"
)

type Category struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Product struct {
	ID         int64     `json:"id"`
	Name       string    `json:"name"`
	Size       string    `json:"size"`
	Weight     int64     `json:"weight"`
	Price      int64     `json:"price"`
	CategoryID int64     `json:"category_id"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
	UserID     int64     `json:"user_id"`
}

type User struct {
	ID                int64     `json:"id"`
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	ChangedPasswordAt time.Time `json:"changed_password_at"`
	CreatedAt         time.Time `json:"created_at"`
	Role              string    `json:"role"`
}
